name: add_issue

on:
  issues:
    types:
      - opened

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "2024"
      - env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-assignee "yeslee5004"
