name: Issue Labeler

on:
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write 

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/checkout@v2
        with:
          repository: actions/checkout
          ref: v2

      - name: Add labels and assignees to issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh issue edit ${{ github.event.issue.number }} --add-label "2024" --add-assignee "yeslee-v"